name: Build and Deploy Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run-script deploy
        
      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --no-silent --dir=dist/browser
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          ACTIONS_STEP_DEBUG: true
